### ISSUE TITLE
训练和测试报错

### ISSUE THREAD

**Issue by swordqiqi** [ljy0ustc/LLaRA#10]
作者您好，训练和测试都有同样的报错，如下，请问该如何解决呢？

(llara) root@autodl-container-a6d5119dfa-c6a4616b:~/autodl-tmp/LLaRA# sh test_movielens.sh
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
Global seed set to 1234
Loading LLAMA
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.65s/it]
trainable params: 19988480 || all params: 6758445056 || trainable%: 0.2957556040535487
Loading LLAMA Done
Loading Rec Model
Loding Rec model Done
load checkpoints from ./checkpoint/movielens.ckpt
Load 3 training prompts
Prompt Example 
This user has watched [HistoryHere] in the previous. Given the following 10 movie titles: [CansHere], recommend one movie for this user to watch next. The movie title you recommend is:
Traceback (most recent call last):
  File "/root/autodl-tmp/LLaRA/main.py", line 141, in <module>
    main(args)
  File "/root/autodl-tmp/LLaRA/main.py", line 57, in main
    trainer = Trainer.from_argparse_args(args)
  File "/root/miniconda3/envs/llara/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1954, in from_argparse_args
    return from_argparse_args(cls, args, **kwargs)
  File "/root/miniconda3/envs/llara/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 66, in from_argparse_args
    return cls(**trainer_kwargs)
  File "/root/miniconda3/envs/llara/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 340, in insert_env_defaults
    return fn(self, **kwargs)
  File "/root/miniconda3/envs/llara/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 414, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/root/miniconda3/envs/llara/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 206, in __init__
    self._accelerator_flag = self._choose_gpu_accelerator_backend()
  File "/root/miniconda3/envs/llara/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 512, in _choose_gpu_accelerator_backend
    raise MisconfigurationException("No supported gpu backend found!")
lightning_lite.utilities.exceptions.MisconfigurationException: No supported gpu backend found!

**Comment by swordqiqi** [comment]
我认为是因为
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable. 但是我不知道怎么解决。请问应该如何解决？谢谢您
